Repository jun950829/TRACKY-FE, pull requests merged in 2025-04, with the labels that each got.

#6 feat: #2 차량 수정 & 차량 삭제 기능 추가
  src/constants/types.ts
  src/libs/apis/carApi.ts
  src/pages/car/CarRegister.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/car/CarUpdateModal.tsx
Labels: Feature

#18 차량/렌트 등록 페이지 ui 수정
  src/Routing.tsx
  src/components/Header.tsx
  src/components/custom/Btn.stories.tsx
  src/components/custom/Btn.tsx
  src/components/custom/CustomButton.stories.tsx
  src/components/custom/CustomButton.tsx
  src/components/custom/Modal.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#20 대시 보드 기본 틀잡기
  src/Routing.tsx
  src/components/Header.tsx
  src/components/custom/Btn.stories.tsx
  src/components/custom/Btn.tsx
  src/components/custom/CustomButton.stories.tsx
  src/components/custom/CustomButton.tsx
  src/components/custom/Modal.tsx
  src/index.css
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/dashboard/DashBoard.tsx
  src/pages/dashboard/DashboardLayout.tsx
  src/pages/dashboard/RecentActivity.tsx
  src/pages/dashboard/ReservationCard.tsx
  src/pages/dashboard/Stats.tsx
  src/pages/dashboard/VehicleMap.tsx
  src/pages/dashboard/VehicleStatusCard.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#22 차량 검색 필터링 기능 추가 / 등록 조회 페이지 리팩토링
  src/components/custom/StatusBadge.stories.tsx
  src/components/custom/StatusBadge.tsx
  src/constants/status.ts
  src/libs/apis/carApi.ts
  src/libs/utils/getClassUtils.ts
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#24 Develop to Main 메인 최신화
  src/components/custom/StatusBadge.stories.tsx
  src/components/custom/StatusBadge.tsx
  src/constants/status.ts
  src/libs/apis/carApi.ts
  src/libs/utils/getClassUtils.ts
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#26 프론트 라우팅 주소로 들어갈때 404오류 수정 및 로그인 정보에 따른 화면 이동 수정
  .env
  src/Routing.tsx
  src/components/Header.tsx
  src/components/PrivateRoute.tsx
  src/components/custom/StatusBadge.stories.tsx
  src/constants/datas/emulatorSettings.ts
  src/constants/datas/menus.ts
  src/constants/datas/status.ts
  src/constants/types/types.ts
  src/libs/apis/carApi.ts
  src/libs/apis/hubApi.ts
  src/libs/apis/rentsApi.ts
  src/libs/utils/getClassUtils.ts
  src/libs/utils/gpsUtils.ts
  src/pages/Home.tsx
  src/pages/car/CarDetailModal.tsx
  src/pages/car/CarRegister.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/car/CarUpdateModal.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/Stats.tsx
  src/pages/dashboard/VehicleStatusCard.tsx
  src/pages/emulator/Emulator.css
  src/pages/emulator/Emulator.tsx
  src/pages/rent/RentDetailModal.tsx
  src/pages/rent/RentRegister.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
  src/pages/rent/RentUpdateModal.tsx
Labels: Feature

#28 fix: 차량 등록 수정 / mdn 관련 세팅 변경
  src/libs/apis/carApi.ts
  src/pages/car/CarRegister.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/car/CarUpdateModal.tsx
Labels: Feature

#29 Develop to Main
  .env
  src/Routing.tsx
  src/components/Header.tsx
  src/components/PrivateRoute.tsx
  src/components/custom/StatusBadge.stories.tsx
  src/constants/datas/emulatorSettings.ts
  src/constants/datas/menus.ts
  src/constants/datas/status.ts
  src/constants/types/types.ts
  src/libs/apis/carApi.ts
  src/libs/apis/hubApi.ts
  src/libs/apis/rentsApi.ts
  src/libs/utils/getClassUtils.ts
  src/libs/utils/gpsUtils.ts
  src/pages/Home.tsx
  src/pages/car/CarDetailModal.tsx
  src/pages/car/CarRegister.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/car/CarUpdateModal.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/Stats.tsx
  src/pages/dashboard/VehicleStatusCard.tsx
  src/pages/emulator/Emulator.css
  src/pages/emulator/Emulator.tsx
  src/pages/rent/RentDetailModal.tsx
  src/pages/rent/RentRegister.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
  src/pages/rent/RentUpdateModal.tsx
Labels: Feature

#31 Feat/rent search update
  src/constants/datas/status.ts
  src/constants/mocks/mockGpsData.ts
  src/libs/apis/carApi.ts
  src/libs/apis/rentsApi.ts
  src/libs/utils/utils.ts
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/emulator/Emulator.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#33 사용자 조회 페이지 / 운행 정보 페이지 작업을 위한 frame & mock data 세팅만
  package-lock.json
  package.json
  src/App.tsx
  src/Routing.tsx
  src/components/AdminRoute.tsx
  src/components/ui/drawer.tsx
  src/components/ui/sheet.tsx
  src/constants/datas/menus.ts
  src/constants/mocks/customRoutes.ts
  src/constants/mocks/historyMockData.ts
  src/constants/mocks/infoMockData.ts
  src/libs/apis/rentsApi.ts
  src/pages/admin/AdminMain.tsx
  src/pages/history/HistoryDetail.tsx
  src/pages/history/HistoryList.tsx
  src/pages/history/HistoryMain.tsx
  src/pages/history/HistoryMap.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/info/InfoMain.tsx
  src/pages/info/InfoResultSection.tsx
  src/pages/info/InfoSearchSection.tsx
  src/pages/rent/RentTable.tsx
  src/stores/useHistoryStore.ts
  src/stores/useInfoStore.ts
Labels: Feature

#34 Develop to Main
  package-lock.json
  package.json
  src/App.tsx
  src/Routing.tsx
  src/components/AdminRoute.tsx
  src/components/ui/drawer.tsx
  src/components/ui/sheet.tsx
  src/constants/datas/menus.ts
  src/constants/datas/status.ts
  src/constants/mocks/customRoutes.ts
  src/constants/mocks/historyMockData.ts
  src/constants/mocks/infoMockData.ts
  src/constants/mocks/mockGpsData.ts
  src/libs/apis/carApi.ts
  src/libs/apis/rentsApi.ts
  src/libs/utils/utils.ts
  src/pages/admin/AdminMain.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/emulator/Emulator.tsx
  src/pages/history/HistoryDetail.tsx
  src/pages/history/HistoryList.tsx
  src/pages/history/HistoryMain.tsx
  src/pages/history/HistoryMap.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/info/InfoMain.tsx
  src/pages/info/InfoResultSection.tsx
  src/pages/info/InfoSearchSection.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
  src/stores/useHistoryStore.ts
  src/stores/useInfoStore.ts
Labels: Feature

#36 WEB - token expire check && meta data set
  index.html
  public/icons/tracky_favicon.png
  public/tracky_logo.png
  public/vite.svg
  src/libs/apis/api.ts
  src/libs/apis/bizApi.ts
  src/libs/apis/hubApi.ts
  src/libs/apis/loginApi.ts
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Feature

#37 Develop to Main
  index.html
  public/icons/tracky_favicon.png
  public/tracky_logo.png
  public/vite.svg
  src/Routing.tsx
  src/components/Header.tsx
  src/libs/apis/api.ts
  src/libs/apis/bizApi.ts
  src/libs/apis/hubApi.ts
  src/libs/apis/loginApi.ts
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: Feature

#39 Feat/dashboard car api
  src/components/custom/StatusBadge.stories.tsx
  src/components/custom/StatusBadge.tsx
  src/constants/datas/icons.tsx
  src/constants/datas/status.ts
  src/constants/types/types.ts
  src/libs/apis/dashboardApi.ts
  src/libs/utils/dashboardUtils.tsx
  src/libs/utils/getClassUtils.ts
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/components/VehicleStatusCards.tsx
  src/pages/info/InfoResultSection.tsx
Labels: Feature

#40 WEB - 대시보드 예약 현황까지 작업
  src/components/Header.tsx
  src/constants/datas/icons.tsx
  src/constants/types/types.ts
  src/libs/apis/dashboardApi.ts
  src/libs/utils/dashboardUtils.tsx
  src/libs/utils/useLogout.ts
  src/pages/Login.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/ReservationCard.tsx
  src/pages/dashboard/components/VehicleStatusCards.tsx
Labels: Feature

#43 대시보드 통계 자료 ui 정상화 // api 연결
  src/constants/types/reservation.ts
  src/constants/types/types.ts
  src/libs/apis/dashboardApi.ts
  src/libs/utils/dashboardUtils.tsx
  src/libs/utils/reservationUtils.ts
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/components/DashBoardCarousel.tsx
  src/pages/dashboard/components/ReservationCard.tsx
Labels: Feature

#45 WEB - 대시보드 최근 기록 붙이기
  src/App.tsx
  src/constants/types/types.ts
  src/hooks/useSseEvents.ts
  src/libs/utils/dashboardUtils.tsx
  src/pages/car/CarRegister.tsx
  src/pages/car/CarUpdateModal.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/RecentActivity.tsx
  src/stores/useSseStore.ts
  vite.config.ts
Labels: Feature

#46 Develop to Main
  src/App.tsx
  src/components/Header.tsx
  src/components/custom/StatusBadge.stories.tsx
  src/components/custom/StatusBadge.tsx
  src/constants/datas/status.ts
  src/constants/types/reservation.ts
  src/constants/types/types.ts
  src/hooks/useSseEvents.ts
  src/libs/apis/dashboardApi.ts
  src/libs/apis/infoApi.ts
  src/libs/utils/dashboardUtils.tsx
  src/libs/utils/getClassUtils.ts
  src/libs/utils/reservationUtils.ts
  src/libs/utils/reverseGeocode.ts
  src/libs/utils/useLogout.ts
  src/pages/Login.tsx
  src/pages/car/CarRegister.tsx
  src/pages/car/CarUpdateModal.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/RecentActivity.tsx
  src/pages/dashboard/components/DashBoardCarousel.tsx
  src/pages/dashboard/components/ReservationCard.tsx
  src/pages/dashboard/components/VehicleStatusCards.tsx
  src/pages/info/InfoMain.tsx
  src/pages/info/InfoResultSection.tsx
  src/pages/info/InfoSearchSection.tsx
  src/stores/useInfoStore.ts
  src/stores/useSseStore.ts
  vite.config.ts
Labels: Feature

#47 WEB - 대시보드 완전 최신화
  public/geojson/korea-provinces.geojson
  src/libs/apis/dashboardApi.ts
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/KoreaMap.tsx
  src/pages/dashboard/MapLayer.tsx
  src/pages/dashboard/VehicleMap.tsx
Labels: Feature

#48 Develop to Main
  public/geojson/korea-provinces.geojson
  src/libs/apis/dashboardApi.ts
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/KoreaMap.tsx
  src/pages/dashboard/MapLayer.tsx
  src/pages/dashboard/VehicleMap.tsx
Labels: Feature

#50 WEB - 예약 등록 수정 시 mdn, 예약 상태 select box 처리
  src/libs/apis/rentsApi.ts
  src/pages/rent/RentRegister.tsx
  src/pages/rent/RentUpdateModal.tsx
Labels: Feature

#52 feat: 운행기록 ui 수정, 에뮬레이터 수정, dashboard 지도 ui 오류 수정
  src/pages/dashboard/RecentActivity.tsx
  src/pages/history/HistoryDrawer.tsx
  src/pages/history/HistoryList.tsx
  src/pages/history/HistoryMain.tsx
Labels: Feature

#55 feat: 운행 정보 예약 list drawer ui 수정
  src/pages/history/HistoryList.tsx
  src/pages/history/HistorySearch.tsx
Labels: Feature

#57 fix #56 차량관리 페이지 QA
  src/pages/car/CarDetailModal.tsx
  src/pages/car/CarRegister.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarTable.tsx
Labels: Bug

#60 WEB - 렌트 수정 시 버그 해결
  src/pages/car/CarRegister.tsx
  src/pages/rent/RentUpdateModal.tsx
Labels: Bug

#61 fix #59 렌트관리 페이지 디테일 수정
  src/components/custom/StatusBadge.tsx
  src/constants/datas/status.ts
  src/libs/utils/utils.ts
  src/pages/rent/RentDetailModal.tsx
  src/pages/rent/RentRegister.tsx
  src/pages/rent/RentTable.tsx
  src/pages/rent/RentUpdateModal.tsx
Labels: Bug

#65 Develop to Main
  package.json
  src/Routing.tsx
  src/constants/mocks/historyMockData.ts
  src/libs/apis/drivehistoryApi.ts
  src/libs/utils/historyUtils.ts
  src/pages/history/HistoryCarList.tsx
  src/pages/history/HistoryDetail.tsx
  src/pages/history/HistoryMain.tsx
  src/pages/history/HistoryMap.tsx
  src/pages/history/HistoryRentList.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/history/HistorySheet.tsx
  src/pages/history/components/MapView.tsx
  src/stores/useHistoryStore.ts
Labels: Feature

#76 feat: sidebar - responsive
  src/App.tsx
  src/components/Sidebar.tsx
Labels: Feature

#91 WEB - Login 페이지 Notice 리스트 출력
  src/pages/Login.tsx
Labels: Feature

#98 WEB - Fix/layer fix
  src/pages/admin/notice/NoticeSection.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/DashboardLayout.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/pages/rent/RentSection.tsx
  src/pages/rent/RentTable.tsx
  src/pages/rent/register/RentRegister.tsx
Labels: Feature, Refactor

#93 WEB - 일반 유저 공지사항 페이지 구현
  src/components/custom/Pagination.tsx
  src/components/routing/Routing.tsx
  src/constants/datas/menus.ts
  src/pages/Login.tsx
  src/pages/admin/notice/AdminNoticeMain.tsx
  src/pages/etc/notice/NoticeMain.tsx
  src/pages/etc/notice/NoticeSearchLayer.tsx
  src/pages/etc/notice/NoticeSection.tsx
  src/pages/etc/notice/NoticeTable.tsx
  src/pages/etc/notice/modal/NoticeDetailModal.tsx
Labels: Feature, Refactor

#101 운행기록 차량 / 차량+ 사용자별 운행기록 조회까지 +++ ui 수정
  src/components/Layout.tsx
  src/components/Sidebar.tsx
  src/components/custom/Pagination.tsx
  src/constants/types/historyTypes.ts
  src/libs/apis/driveApi.ts
  src/pages/admin/member/AdminMemberSection.tsx
  src/pages/admin/notice/AdminNoticeMain.tsx
  src/pages/admin/notice/NoticeSection.tsx
  src/pages/car/CarMain.tsx
  src/pages/car/CarSection.tsx
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/DashboardLayout.tsx
  src/pages/dashboard/components/ReturnedStatus.tsx
  src/pages/history/HistoryCarLayer.tsx
  src/pages/history/HistoryCarList.tsx
  src/pages/history/HistoryMain.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/history/HistorySection.tsx
  src/pages/history/HistoryTable.tsx
  src/pages/rent/RentMain.tsx
  src/pages/rent/RentSection.tsx
  src/stores/useCarListStore.ts
  src/stores/useDriveListStore.ts
Labels: Feature

#102 WEB - 운행기록 주행리스트
  src/libs/apis/driveApi.ts
  src/pages/dashboard/DashBoardMain.tsx
  src/pages/dashboard/components/ReturnedStatus.tsx
  src/pages/history/HistoryCarList.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/history/HistorySection.tsx
  src/pages/history/HistoryTable.tsx
  src/stores/useDriveListStore.ts
Labels: Feature

#110 WEB - 차량 soft delete 추가 및 update modal logic fix & 불필요한 log 제거
  src/hooks/useSseEvents.ts
  src/libs/apis/carApi.ts
  src/libs/utils/getClassUtils.ts
  src/libs/utils/gpsBuffer.ts
  src/pages/Home.tsx
  src/pages/admin/notice/NoticeTable.tsx
  src/pages/car/CarSection.tsx
  src/pages/car/CarTable.tsx
  src/pages/car/CarUpdateModal.tsx
  src/pages/car/register/CarRegister.tsx
  src/pages/emulator/Emulator.tsx
  src/pages/etc/notice/NoticeSection.tsx
  src/pages/etc/notice/NoticeTable.tsx
  src/pages/history/HistoryTable.tsx
  src/pages/rent/RentDetailModal.tsx
  src/pages/rent/RentTable.tsx
Labels: Feature

#113 feat: rent table 총 개수 설정
  src/constants/datas/options.ts
  src/pages/car/CarSearchLayer.tsx
  src/pages/rent/RentSearchLayer.tsx
  src/stores/useCarListStore.ts
Labels: Feature

#115 feat: rent address 추가
  package.json
  src/components/address/AddressSearch.tsx
  src/components/ui/scroll-area.tsx
  src/hooks/useAddressSearch.ts
  src/libs/apis/addressApi.ts
  src/libs/utils.ts
  src/libs/utils/utils.ts
  src/pages/rent/register/RentRegister.tsx
Labels: Feature

#119 WEB - Excel 추출 기능 추가
  src/libs/apis/carApi.ts
  src/libs/apis/driveApi.ts
  src/pages/car/CarSearchLayer.tsx
  src/pages/car/CarSection.tsx
  src/pages/history/HistoryTable.tsx
Labels: Feature

#120 WEB - 운행기록 중복 호출 해결
  src/pages/history/HistoryCarList.tsx
  src/stores/useDriveListStore.ts
Labels: Feature

#121 Fix/UI error fix
  src/components/Sidebar.tsx
  src/constants/datas/menus.ts
  src/pages/admin/member/MemberModal.tsx
  src/pages/admin/notice/AdminNoticeMain.tsx
  src/pages/admin/notice/NoticeSearchLayer.tsx
  src/pages/admin/notice/NoticeSection.tsx
  src/pages/admin/notice/NoticeTable.tsx
  src/pages/car/CarDetailModal.tsx
  src/pages/car/CarSearchLayer.tsx
  src/pages/etc/notice/NoticeMain.tsx
  src/pages/etc/notice/NoticeSearchLayer.tsx
  src/pages/etc/notice/NoticeSection.tsx
  src/pages/etc/notice/NoticeTable.tsx
  src/pages/history/HistoryCarList.tsx
  src/pages/history/HistorySearch.tsx
  src/pages/history/detail/HistoryDetailPage.tsx
  src/pages/history/detail/HistoryMap.tsx
  src/pages/rent/RentDetailModal.tsx
Labels: Feature
